### ISSUE TITLE
Missing `.gitignore` file and unnecessary directories

### ISSUE THREAD

**Issue by mertssmnoglu** [Artado-Project/artadobot#2]
There is no `.gitignore` file in the repo and this can cause accidentally pushing some file/dir to repo.

Some unwanted directories are
`.idea` | User's jetbrains(pycharm) configuration
`artadobot-env` | User's whole python environment

You can check GitHub's [Python Gitignore Template](https://github.com/github/gitignore/blob/main/Python.gitignore)

**Comment by yasinldev** [comment]
project is being renewed
